import json
from pathlib import Path

from config.settings import Settings
from core.file_generator import FileGenerator
from core.folder_creator import FolderCreator
from core.placeholder_engine import PlaceholderEngine
from core.template_engine import TemplateEngine
from models.project_model import ProjectModel


class ProjectGenerator:

    @staticmethod
    def generate(project: ProjectModel):

        # Create folder structure
        FolderCreator.create(project)

        # Read template manifest
        manifest_path = Settings.TEMPLATE_FOLDER / "odata" / "template.json"

        manifest = json.loads(TemplateEngine.read(manifest_path))

        # Generate every file defined in template.json
        for template_info in manifest["templates"]:

            template_path = (
                Settings.TEMPLATE_FOLDER / "odata" / template_info["template"]
            )

            target = PlaceholderEngine.replace(template_info["target"], project)
            output = PlaceholderEngine.replace(template_info["output"], project)
            output_file = Settings.OUTPUT_FOLDER / target / output

            # "onceOnly" files (currently just <Name>BusinessLogic.java) are
            # generated the first time a project exists and never touched
            # again -- that's where hand-written business logic lives, and
            # regenerating must not be able to overwrite it.
            if template_info.get("onceOnly") and output_file.exists():
                print(f"Skipped (already exists, hand-owned): {output_file}")
                continue

            # --------------------------------------------
            # Java files are generated by Java Builder
            # --------------------------------------------
            if template_info["template"] == "java/java_helper.template":

                from core.java_class_generator import JavaClassGenerator

                generated_content = JavaClassGenerator.generate(project)

            elif template_info["template"] == "java/business_logic.template":

                from core.java.business_logic_generator import BusinessLogicGenerator

                generated_content = BusinessLogicGenerator.generate(project)

            elif template_info["template"] == "java/sps_modification_list.template":

                from core.java.dto_generator import DTOGenerator

                generated_content = DTOGenerator.generate(project)

            elif template_info["template"] == "complexType/output_schema.template":

                from core.schema_generator import SchemaGenerator

                generated_content = SchemaGenerator.generate(project)

            else:

                template_content = TemplateEngine.read(template_path)

                generated_content = PlaceholderEngine.replace(template_content, project)

            FileGenerator.write(output_file, generated_content)

            print(f"Generated : {output_file}")
